#![cfg(test)]

use creditra_credit::types::{ContractError, ContractErrorCategory};

#[test]
fn test_from_u32_safe_known_codes() {
    assert_eq!(ContractError::from_u32_safe(1), ContractError::Unauthorized);
    assert_eq!(ContractError::from_u32_safe(2), ContractError::NotAdmin);
    assert_eq!(
        ContractError::from_u32_safe(3),
        ContractError::CreditLineNotFound
    );
    assert_eq!(
        ContractError::from_u32_safe(4),
        ContractError::CreditLineClosed
    );
    assert_eq!(
        ContractError::from_u32_safe(5),
        ContractError::InvalidAmount
    );
    assert_eq!(ContractError::from_u32_safe(6), ContractError::OverLimit);
    assert_eq!(
        ContractError::from_u32_safe(7),
        ContractError::NegativeLimit
    );
    assert_eq!(ContractError::from_u32_safe(8), ContractError::RateTooHigh);
    assert_eq!(ContractError::from_u32_safe(9), ContractError::ScoreTooHigh);
    assert_eq!(
        ContractError::from_u32_safe(10),
        ContractError::UtilizationNotZero
    );
    assert_eq!(ContractError::from_u32_safe(11), ContractError::Reentrancy);
    assert_eq!(ContractError::from_u32_safe(12), ContractError::Overflow);
    assert_eq!(
        ContractError::from_u32_safe(13),
        ContractError::LimitDecreaseRequiresRepayment
    );
    assert_eq!(
        ContractError::from_u32_safe(14),
        ContractError::AlreadyInitialized
    );
    assert_eq!(
        ContractError::from_u32_safe(15),
        ContractError::AdminAcceptTooEarly
    );
    assert_eq!(
        ContractError::from_u32_safe(16),
        ContractError::BorrowerBlocked
    );
    assert_eq!(
        ContractError::from_u32_safe(17),
        ContractError::DrawExceedsMaxAmount
    );
    assert_eq!(ContractError::from_u32_safe(18), ContractError::Paused);
    assert_eq!(ContractError::from_u32_safe(19), ContractError::DrawsFrozen);
    assert_eq!(
        ContractError::from_u32_safe(20),
        ContractError::CreditLineSuspended
    );
    assert_eq!(
        ContractError::from_u32_safe(21),
        ContractError::CreditLineDefaulted
    );
    assert_eq!(
        ContractError::from_u32_safe(22),
        ContractError::MissingLiquidityToken
    );
    assert_eq!(
        ContractError::from_u32_safe(23),
        ContractError::MissingLiquiditySource
    );
    assert_eq!(
        ContractError::from_u32_safe(24),
        ContractError::InsufficientLiquidityReserve
    );
    assert_eq!(
        ContractError::from_u32_safe(25),
        ContractError::LiquidityTokenCallFailed
    );
    assert_eq!(
        ContractError::from_u32_safe(26),
        ContractError::InsufficientRepaymentAllowance
    );
    assert_eq!(
        ContractError::from_u32_safe(27),
        ContractError::InsufficientRepaymentBalance
    );
    assert_eq!(
        ContractError::from_u32_safe(28),
        ContractError::RepayExceedsMaxAmount
    );
    assert_eq!(
        ContractError::from_u32_safe(29),
        ContractError::DrawCooldownActive
    );
    assert_eq!(
        ContractError::from_u32_safe(30),
        ContractError::TreasuryNotSet
    );
    assert_eq!(
        ContractError::from_u32_safe(31),
        ContractError::ExposureCapExceeded
    );
    assert_eq!(
        ContractError::from_u32_safe(32),
        ContractError::AdminNotInitialized
    );
    assert_eq!(
        ContractError::from_u32_safe(33),
        ContractError::TimestampRegression
    );
    assert_eq!(
        ContractError::from_u32_safe(34),
        ContractError::LimitOutOfBounds
    );
    assert_eq!(
        ContractError::from_u32_safe(35),
        ContractError::CollateralRatioBelowMinimum
    );
    assert_eq!(
        ContractError::from_u32_safe(36),
        ContractError::OraclePriceInvalid
    );
    assert_eq!(
        ContractError::from_u32_safe(37),
        ContractError::OraclePriceStale
    );
    assert_eq!(
        ContractError::from_u32_safe(38),
        ContractError::OraclePriceDeviation
    );
    assert_eq!(
        ContractError::from_u32_safe(39),
        ContractError::InsufficientCollateralBalance
    );
    assert_eq!(
        ContractError::from_u32_safe(40),
        ContractError::BorrowerFrozen
    );
    assert_eq!(
        ContractError::from_u32_safe(41),
        ContractError::BountyNotSet
    );
    assert_eq!(
        ContractError::from_u32_safe(42),
        ContractError::NoPendingTreasuryWithdrawal
    );
    assert_eq!(
        ContractError::from_u32_safe(43),
        ContractError::BorrowerExposureCapExceeded
    );
    assert_eq!(
        ContractError::from_u32_safe(46),
        ContractError::CreditLineFrozen
    );
    assert_eq!(
        ContractError::from_u32_safe(47),
        ContractError::DrawReversalWindowExpired
    );
    assert_eq!(
        ContractError::from_u32_safe(48),
        ContractError::OriginalDrawNotFound
    );
    assert_eq!(
        ContractError::from_u32_safe(49),
        ContractError::AttestationBatchNotFound
    );
    assert_eq!(
        ContractError::from_u32_safe(50),
        ContractError::OracleQuorumNotMet
    );
    assert_eq!(
        ContractError::from_u32_safe(51),
        ContractError::AlreadySettled
    );
    assert_eq!(
        ContractError::from_u32_safe(52),
        ContractError::InvalidRiskWeight
    );
    assert_eq!(
        ContractError::from_u32_safe(53),
        ContractError::InvalidAttestation
    );
    assert_eq!(
        ContractError::from_u32_safe(54),
        ContractError::RiskAdminCooldownActive
    );
    assert_eq!(
        ContractError::from_u32_safe(55),
        ContractError::OracleNotFound
    );
    assert_eq!(
        ContractError::from_u32_safe(57),
        ContractError::FreezeCooldownActive
    );
    assert_eq!(
        ContractError::from_u32_safe(58),
        ContractError::AdminCollateralCooldownActive
    );
    assert_eq!(
        ContractError::from_u32_safe(59),
        ContractError::LiquidationGraceActive
    );
    assert_eq!(
        ContractError::from_u32_safe(60),
        ContractError::UnknownError
    );
}

#[test]
fn test_from_u32_safe_unknown_codes_fallback() {
    assert_eq!(ContractError::from_u32_safe(0), ContractError::UnknownError);
    assert_eq!(
        ContractError::from_u32_safe(44),
        ContractError::UnknownError
    );
    assert_eq!(
        ContractError::from_u32_safe(45),
        ContractError::UnknownError
    );
    assert_eq!(
        ContractError::from_u32_safe(56),
        ContractError::UnknownError
    );
    assert_eq!(
        ContractError::from_u32_safe(999),
        ContractError::UnknownError
    );
    assert_eq!(
        ContractError::from_u32_safe(u32::MAX),
        ContractError::UnknownError
    );
}

#[test]
fn variant_count_is_known() {
    let variants = vec![
        ContractError::Unauthorized,
        ContractError::NotAdmin,
        ContractError::CreditLineNotFound,
        ContractError::CreditLineClosed,
        ContractError::InvalidAmount,
        ContractError::OverLimit,
        ContractError::NegativeLimit,
        ContractError::RateTooHigh,
        ContractError::ScoreTooHigh,
        ContractError::UtilizationNotZero,
        ContractError::Reentrancy,
        ContractError::Overflow,
        ContractError::LimitDecreaseRequiresRepayment,
        ContractError::AlreadyInitialized,
        ContractError::AdminAcceptTooEarly,
        ContractError::BorrowerBlocked,
        ContractError::DrawExceedsMaxAmount,
        ContractError::Paused,
        ContractError::DrawsFrozen,
        ContractError::CreditLineSuspended,
        ContractError::CreditLineDefaulted,
        ContractError::MissingLiquidityToken,
        ContractError::MissingLiquiditySource,
        ContractError::InsufficientLiquidityReserve,
        ContractError::LiquidityTokenCallFailed,
        ContractError::InsufficientRepaymentAllowance,
        ContractError::InsufficientRepaymentBalance,
        ContractError::RepayExceedsMaxAmount,
        ContractError::DrawCooldownActive,
        ContractError::TreasuryNotSet,
        ContractError::ExposureCapExceeded,
        ContractError::AdminNotInitialized,
        ContractError::TimestampRegression,
        ContractError::LimitOutOfBounds,
        ContractError::CollateralRatioBelowMinimum,
        ContractError::OraclePriceInvalid,
        ContractError::OraclePriceStale,
        ContractError::OraclePriceDeviation,
        ContractError::InsufficientCollateralBalance,
        ContractError::BorrowerFrozen,
        ContractError::BountyNotSet,
        ContractError::NoPendingTreasuryWithdrawal,
        ContractError::BorrowerExposureCapExceeded,
        ContractError::CreditLineFrozen,
        ContractError::DrawReversalWindowExpired,
        ContractError::OriginalDrawNotFound,
        ContractError::AttestationBatchNotFound,
        ContractError::OracleQuorumNotMet,
        ContractError::AlreadySettled,
        ContractError::InvalidRiskWeight,
        ContractError::InvalidAttestation,
        ContractError::RiskAdminCooldownActive,
        ContractError::OracleNotFound,
        ContractError::FreezeCooldownActive,
        ContractError::AdminCollateralCooldownActive,
        ContractError::LiquidationGraceActive,
        ContractError::UnknownError,
    ];
    assert_eq!(variants.len(), 57, "Variant count must remain stable");
}
