// SPDX-License-Identifier: MIT

//! Property-based tests for query (v7) state invariants.
//!
//! # What
//!
//! Generates random credit-line configurations, utilization levels, and
//! repayment schedule parameters, then verifies that key query-subsystem
//! invariants hold for every generated input.
//!
//! # Invariants
//!
//! 1. **Capabilities bitmap consistency**: Every field in [`QueryCapabilities`]
//!    is derived deterministically from storage state. The same borrower
//!    address always yields the same bitmap when the underlying state has not
//!    changed.
//! 2. **`query_capabilities` determinism**: Consecutive calls with the same
//!    borrower and unchanged state must return identical bitmaps.
//! 3. **Health-factor sentinel**: `get_health_factor` returns `u32::MAX` when
//!    `utilized_amount == 0`; it returns a finite value when
//!    `utilized_amount > 0`.
//! 4. **`is_delinquent` short-circuit**: `is_delinquent` must return `false`
//!    when there is no credit line, the line is `Closed`, `utilized_amount`
//!    is zero, or there is no repayment schedule.
//! 5. **`get_protocol_summary` non-negative**: `count` and `total_utilized`
//!    returned by `get_protocol_summary` are never negative after any sequence
//!    of open/draw/repay operations.
//! 6. **`get_credit_line` idempotency**: A pure read must return the same
//!    value on two consecutive calls when no state mutation occurs between
//!    them.
//!
//! # Covered paths
//!
//! | Path                     | Why it matters                                    |
//! |--------------------------|---------------------------------------------------|
//! | `query_capabilities`     | Bitmap correctness across all state configurations|
//! | `get_credit_line`        | Idempotent read; consistent with capabilities     |
//! | `get_health_factor`      | Sentinel (`u32::MAX`) for zero debt; finite value |
//! | `is_delinquent`          | Short-circuit paths and schedule interaction      |
//! | `get_protocol_summary`   | Aggregate non-negativity after mutations          |
//! | `set_repayment_schedule` | Schedule presence drives delinquency_applicable   |
//!
//! # See also
//!
//! - `contracts/query/tests/capabilities.rs` — deterministic capabilities tests.
//! - `contracts/query/tests/rustdoc_query_tests.rs` — rustdoc coverage tests.
//! - `contracts/accrual/tests/proptest.rs` — accrual invariant proptest pattern.
//! - `contracts/risk/tests/proptest.rs` — risk invariant proptest pattern.

extern crate std;

use creditra_credit::types::CreditStatus;
use creditra_credit::{Credit, CreditClient};
use proptest::prelude::*;
use proptest::test_runner::Config as ProptestConfig;
use soroban_sdk::testutils::{Address as _, Ledger};
use soroban_sdk::token::StellarAssetClient;
use soroban_sdk::{Address, Env};

// ── Constants ─────────────────────────────────────────────────────────────────

const INITIAL_TIMESTAMP: u64 = 1_000_000;
/// Liquidity pre-minted into the contract for draw tests.
const LIQUIDITY_AMOUNT: i128 = 100_000_000;
/// Maximum credit limit generated by strategies (keeps test fast).
const MAX_CREDIT_LIMIT: i128 = 500_000;
/// Maximum draw amount in draw-based strategies.
const MAX_DRAW: i128 = 100_000;

// ── Setup helpers ─────────────────────────────────────────────────────────────

/// Create a minimal test environment with a Credit contract and admin.
///
/// Returns `(env, client, admin)` ready for non-draw tests that do not
/// require a liquidity token.
fn setup_env() -> (Env, CreditClient<'static>, Address) {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(INITIAL_TIMESTAMP);

    let admin = Address::generate(&env);
    let contract_id = env.register(Credit, ());
    let client = CreditClient::new(&env, &contract_id);
    client.init(&admin);

    (env, client, admin)
}

/// Create a test environment with a liquidity token pre-minted so that
/// `draw_credit` calls succeed.
///
/// Returns `(env, client, contract_id, admin)`.
fn setup_with_token() -> (Env, CreditClient<'static>, Address, Address) {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(INITIAL_TIMESTAMP);

    let admin = Address::generate(&env);
    let contract_id = env.register(Credit, ());
    let client = CreditClient::new(&env, &contract_id);
    client.init(&admin);

    // Register and configure liquidity token.
    let token_id = env.register_stellar_asset_contract_v2(Address::generate(&env));
    let token = token_id.address();
    client.set_liquidity_token(&token);
    client.set_liquidity_source(&contract_id);
    // Disable collateral requirement so draws succeed unconditionally.
    client.set_min_collateral_ratio_bps(&0);

    StellarAssetClient::new(&env, &token).mint(&contract_id, &LIQUIDITY_AMOUNT);

    (env, client, contract_id, admin)
}

// ── Invariant assertion helpers ───────────────────────────────────────────────

/// Assert `get_protocol_summary().count >= 0` and
/// `get_protocol_summary().total_utilized >= 0`.
fn assert_protocol_summary_non_negative(client: &CreditClient<'_>, label: &str) {
    let summary = client.get_protocol_summary();
    assert!(
        summary.total_utilized >= 0,
        "{label}: total_utilized is negative: {}",
        summary.total_utilized,
    );
    // count is u32 so it is always >= 0 by type; just document the check.
    let _ = summary.count;
}

/// Assert that `delinquency_applicable = false` implies `is_delinquent = false`.
fn assert_delinquency_gate(client: &CreditClient<'_>, borrower: &Address, label: &str) {
    let caps = client.query_capabilities(borrower);
    if !caps.delinquency_applicable {
        assert!(
            !caps.is_delinquent,
            "{label}: is_delinquent must be false when delinquency_applicable is false",
        );
    }
}

/// Assert that `health_factor_applicable = false` implies `get_health_factor`
/// returns `u32::MAX`.
fn assert_health_factor_sentinel(client: &CreditClient<'_>, borrower: &Address, label: &str) {
    let caps = client.query_capabilities(borrower);
    if !caps.health_factor_applicable {
        let hf = client.get_health_factor(borrower);
        assert_eq!(
            hf,
            u32::MAX,
            "{label}: health_factor must be u32::MAX when not applicable, got {hf}",
        );
    }
}

// ── Strategies ────────────────────────────────────────────────────────────────

/// Generate a valid `(credit_limit, interest_rate_bps, risk_score)` triple.
///
/// - `credit_limit`: 1 .. MAX_CREDIT_LIMIT
/// - `interest_rate_bps`: 1 .. 10_000
/// - `risk_score`: 0 .. 100
fn credit_line_params() -> impl Strategy<Value = (i128, u32, u32)> {
    (
        1_i128..=MAX_CREDIT_LIMIT,
        1_u32..=10_000_u32,
        0_u32..=100_u32,
    )
}

/// Generate a valid draw amount in `1 .. limit`.
fn draw_amount(limit: i128) -> impl Strategy<Value = i128> {
    1_i128..=limit.min(MAX_DRAW).max(1)
}

/// Generate a valid `(amount_per_period, period_seconds, next_due_ts)` schedule.
///
/// - `amount_per_period`: 1 .. 10_000
/// - `period_seconds`: 3600 .. 2_592_000 (1 hour to 30 days)
/// - `next_due_ts`: INITIAL_TIMESTAMP .. INITIAL_TIMESTAMP + 7_776_000 (90 days)
fn schedule_params() -> impl Strategy<Value = (i128, u64, u64)> {
    (
        1_i128..=10_000_i128,
        3_600_u64..=2_592_000_u64,
        INITIAL_TIMESTAMP..=(INITIAL_TIMESTAMP + 7_776_000_u64),
    )
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 1 — Capabilities bitmap consistency: no credit line → all false
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: When a borrower has no credit line, every field in
    /// [`QueryCapabilities`] must be `false`, regardless of the address value.
    ///
    /// This covers the "unknown borrower" short-circuit at the top of the
    /// `capabilities()` view.
    #[test]
    fn prop_no_credit_line_all_capabilities_false(
        // Use the raw bytes to vary the generated address — we ignore this
        // value directly but it forces proptest to generate different envs.
        _seed in 0u64..u64::MAX,
    ) {
        let (env, client, _admin) = setup_env();
        let borrower = Address::generate(&env);

        let caps = client.query_capabilities(&borrower);

        prop_assert!(
            !caps.has_credit_line,
            "no line → has_credit_line must be false",
        );
        prop_assert!(
            !caps.has_repayment_schedule,
            "no line → has_repayment_schedule must be false",
        );
        prop_assert!(
            !caps.health_factor_applicable,
            "no line → health_factor_applicable must be false",
        );
        prop_assert!(
            !caps.delinquency_applicable,
            "no line → delinquency_applicable must be false",
        );
        prop_assert!(
            !caps.is_delinquent,
            "no line → is_delinquent must be false",
        );

        // Confirm health_factor returns u32::MAX for unknown borrowers.
        let hf = client.get_health_factor(&borrower);
        prop_assert_eq!(
            hf,
            u32::MAX,
            "no line → get_health_factor must return u32::MAX, got {hf}",
        );

        // Confirm is_delinquent returns false for unknown borrowers.
        let delinquent = client.is_delinquent(&borrower);
        prop_assert!(
            !delinquent,
            "no line → is_delinquent must be false",
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 2 — Capabilities bitmap with open line, zero utilization
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: An open line with zero utilization must have:
    /// - `has_credit_line = true`
    /// - `health_factor_applicable = false` (zero debt)
    /// - `delinquency_applicable = false` (zero debt)
    /// - `is_delinquent = false`
    /// - `get_health_factor` returns `u32::MAX`
    ///
    /// `has_repayment_schedule` follows whether a schedule was configured;
    /// but `delinquency_applicable` stays false because utilization is zero.
    #[test]
    fn prop_open_line_zero_utilization_capabilities(
        (limit, rate, score) in credit_line_params(),
    ) {
        let (env, client, _admin) = setup_env();
        let borrower = Address::generate(&env);
        client.open_credit_line(&borrower, &limit, &rate, &score);

        let caps = client.query_capabilities(&borrower);

        prop_assert!(caps.has_credit_line, "open line → has_credit_line must be true");
        prop_assert!(
            !caps.health_factor_applicable,
            "zero utilization → health_factor_applicable must be false",
        );
        prop_assert!(
            !caps.delinquency_applicable,
            "zero utilization → delinquency_applicable must be false",
        );
        prop_assert!(!caps.is_delinquent, "zero utilization → is_delinquent must be false");

        // Confirm health_factor returns u32::MAX.
        let hf = client.get_health_factor(&borrower);
        prop_assert_eq!(
            hf,
            u32::MAX,
            "zero utilization → get_health_factor must return u32::MAX, got {hf}",
        );

        // delinquency_applicable → is_delinquent gate.
        assert_delinquency_gate(&client, &borrower, "zero_util");
        assert_health_factor_sentinel(&client, &borrower, "zero_util");
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 3 — query_capabilities determinism
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: Two consecutive calls to `query_capabilities` with the
    /// same borrower and no intervening mutation must return identical bitmaps.
    ///
    /// Covers the pure-read, no-mutation guarantee documented in `views.rs`.
    #[test]
    fn prop_query_capabilities_deterministic(
        (limit, rate, score) in credit_line_params(),
    ) {
        let (env, client, _admin) = setup_env();
        let borrower = Address::generate(&env);
        client.open_credit_line(&borrower, &limit, &rate, &score);

        let caps_a = client.query_capabilities(&borrower);
        let caps_b = client.query_capabilities(&borrower);

        prop_assert_eq!(
            caps_a.has_credit_line,
            caps_b.has_credit_line,
            "has_credit_line must be deterministic",
        );
        prop_assert_eq!(
            caps_a.has_repayment_schedule,
            caps_b.has_repayment_schedule,
            "has_repayment_schedule must be deterministic",
        );
        prop_assert_eq!(
            caps_a.health_factor_applicable,
            caps_b.health_factor_applicable,
            "health_factor_applicable must be deterministic",
        );
        prop_assert_eq!(
            caps_a.delinquency_applicable,
            caps_b.delinquency_applicable,
            "delinquency_applicable must be deterministic",
        );
        prop_assert_eq!(
            caps_a.is_delinquent,
            caps_b.is_delinquent,
            "is_delinquent must be deterministic",
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 4 — Health-factor sentinel: zero utilization → u32::MAX
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: `get_health_factor` must return `u32::MAX` for any
    /// credit line whose `utilized_amount` is zero.
    ///
    /// This covers every open-line configuration at the moment after
    /// `open_credit_line` (before any draw has occurred) with arbitrary
    /// `(limit, rate, score)` parameters.
    #[test]
    fn prop_health_factor_zero_util_returns_max(
        (limit, rate, score) in credit_line_params(),
    ) {
        let (env, client, _admin) = setup_env();
        let borrower = Address::generate(&env);
        client.open_credit_line(&borrower, &limit, &rate, &score);

        // Confirm utilized_amount is zero.
        let line = client.get_credit_line(&borrower).expect("line must exist");
        prop_assert_eq!(
            line.utilized_amount, 0,
            "no draw → utilized_amount must be 0",
        );

        let hf = client.get_health_factor(&borrower);
        prop_assert_eq!(
            hf,
            u32::MAX,
            "zero utilization → get_health_factor must be u32::MAX, got {hf}",
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 5 — Health-factor finite: positive utilization → finite value
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 128,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: After a successful `draw_credit`, `utilized_amount > 0`
    /// and `get_health_factor` must return a finite (non-`u32::MAX`) value
    /// when `min_collateral_ratio_bps > 0` and collateral is zero.
    ///
    /// With zero collateral and positive debt, `health_bps = 0 * 10^8 /
    /// (utilized * ratio) = 0`, confirming the sentinel is only returned for
    /// zero-debt positions.
    #[test]
    fn prop_health_factor_positive_util_returns_finite(
        (limit, rate, score) in credit_line_params(),
        draw_fraction in 1_u32..=100_u32,
    ) {
        let (env, client, _contract_id, _admin) = setup_with_token();
        let borrower = Address::generate(&env);
        client.open_credit_line(&borrower, &limit, &rate, &score);

        // Draw a fraction of the limit (1%–100%).
        let draw = ((limit as u64 * draw_fraction as u64) / 100).max(1) as i128;
        let draw = draw.min(limit).min(MAX_DRAW);
        let result = client.try_draw_credit(&borrower, &draw);

        if result.is_ok() {
            let line = client.get_credit_line(&borrower).expect("line must exist");
            if line.utilized_amount > 0 {
                let hf = client.get_health_factor(&borrower);
                // health_factor_applicable must be true.
                let caps = client.query_capabilities(&borrower);
                prop_assert!(
                    caps.health_factor_applicable,
                    "utilized > 0 → health_factor_applicable must be true",
                );
                // With zero collateral, health factor must be 0 (not u32::MAX).
                prop_assert_ne!(
                    hf,
                    u32::MAX,
                    "positive utilization, zero collateral → health_factor must not be u32::MAX",
                );
            }
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 6 — is_delinquent short-circuit: no schedule → always false
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 128,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: `is_delinquent` must return `false` when there is no
    /// repayment schedule, regardless of utilization level, elapsed time, or
    /// credit line parameters.
    ///
    /// The short-circuit inside `is_delinquent` reads:
    /// ```text
    /// let Some(schedule) = get_repayment_schedule(...) else { return false; };
    /// ```
    #[test]
    fn prop_is_delinquent_false_without_schedule(
        (limit, rate, score) in credit_line_params(),
        time_advance in 0u64..=31_536_000u64,
    ) {
        let (env, client, _contract_id, _admin) = setup_with_token();
        let borrower = Address::generate(&env);
        client.open_credit_line(&borrower, &limit, &rate, &score);

        // Draw some amount to get positive utilization.
        let draw = (limit / 2).max(1).min(MAX_DRAW);
        let _ = client.try_draw_credit(&borrower, &draw);

        // Advance time to simulate elapsed installment periods.
        env.ledger().with_mut(|l| l.timestamp += time_advance);

        // No schedule set — delinquency must be false.
        let delinquent = client.is_delinquent(&borrower);
        prop_assert!(
            !delinquent,
            "no schedule → is_delinquent must be false (time_advance={time_advance}s)",
        );

        let caps = client.query_capabilities(&borrower);
        prop_assert!(
            !caps.delinquency_applicable,
            "no schedule → delinquency_applicable must be false",
        );
        prop_assert!(
            !caps.is_delinquent,
            "no schedule → caps.is_delinquent must be false",
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 7 — is_delinquent: closed line → always false
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 128,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: `is_delinquent` must return `false` for a `Closed`
    /// credit line, even if a repayment schedule was configured before closure.
    ///
    /// The short-circuit inside `is_delinquent` reads:
    /// ```text
    /// if line.status == CreditStatus::Closed || line.utilized_amount <= 0 {
    ///     return false;
    /// }
    /// ```
    #[test]
    fn prop_is_delinquent_false_for_closed_line(
        (limit, rate, score) in credit_line_params(),
        (amt_per_period, period_secs, next_due_ts) in schedule_params(),
        time_advance in 0u64..=7_776_000u64,
    ) {
        let (env, client, _contract_id, admin) = setup_with_token();
        let borrower = Address::generate(&env);
        client.open_credit_line(&borrower, &limit, &rate, &score);

        // Attach a repayment schedule before closing.
        client.set_repayment_schedule(
            &borrower,
            &amt_per_period,
            &period_secs,
            &next_due_ts,
        );

        // Close the line (no draw — zero utilization required for close).
        client.close_credit_line(&borrower, &admin);

        let line = client.get_credit_line(&borrower).expect("closed line must exist");
        prop_assert_eq!(
            line.status,
            CreditStatus::Closed,
            "line must be Closed after close_credit_line",
        );

        // Advance time past the due date.
        env.ledger().with_mut(|l| l.timestamp += time_advance);

        let delinquent = client.is_delinquent(&borrower);
        prop_assert!(
            !delinquent,
            "Closed line → is_delinquent must be false",
        );

        let caps = client.query_capabilities(&borrower);
        prop_assert!(
            !caps.delinquency_applicable,
            "Closed line → delinquency_applicable must be false",
        );
        prop_assert!(
            !caps.is_delinquent,
            "Closed line → caps.is_delinquent must be false",
        );
        // health_factor_applicable must also be false (zero utilization).
        prop_assert!(
            !caps.health_factor_applicable,
            "Closed line with zero util → health_factor_applicable must be false",
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 8 — get_protocol_summary non-negative invariant
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 128,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: `get_protocol_summary().total_utilized` and `.count`
    /// must never be negative after any sequence of open / draw / repay
    /// operations across multiple borrowers.
    ///
    /// Covers the aggregate non-negativity guarantee documented in
    /// `contracts/query/src/lib.rs`.
    #[test]
    fn prop_protocol_summary_non_negative(
        params in proptest::collection::vec(
            credit_line_params(),
            1..=4_usize,
        ),
        draws in proptest::collection::vec(
            1_u32..=80_u32,
            1..=4_usize,
        ),
    ) {
        let (env, client, _contract_id, _admin) = setup_with_token();

        // Assert initial state.
        assert_protocol_summary_non_negative(&client, "initial");

        let mut borrowers: std::vec::Vec<Address> = std::vec::Vec::new();

        // Open credit lines.
        for (i, (limit, rate, score)) in params.iter().enumerate() {
            let borrower = Address::generate(&env);
            client.open_credit_line(&borrower, limit, rate, score);
            borrowers.push(borrower);

            let label = std::format!("after_open[{i}]");
            assert_protocol_summary_non_negative(&client, &label);
        }

        // Draw on each borrower.
        for (i, borrower) in borrowers.iter().enumerate() {
            if let Some(line) = client.get_credit_line(borrower) {
                if line.status == CreditStatus::Active {
                    let fraction = draws.get(i).copied().unwrap_or(50_u32);
                    let draw = ((line.credit_limit as u64 * fraction as u64) / 100)
                        .max(1) as i128;
                    let draw = draw.min(line.credit_limit).min(MAX_DRAW);
                    let _ = client.try_draw_credit(borrower, &draw);
                }
            }
            let label = std::format!("after_draw[{i}]");
            assert_protocol_summary_non_negative(&client, &label);
        }

        // Partial repay on each borrower.
        for (i, borrower) in borrowers.iter().enumerate() {
            if let Some(line) = client.get_credit_line(borrower) {
                if line.utilized_amount > 0 {
                    let repay = (line.utilized_amount / 2).max(1);
                    let _ = client.try_repay_credit(borrower, &repay);
                }
            }
            let label = std::format!("after_repay[{i}]");
            assert_protocol_summary_non_negative(&client, &label);
        }

        // Final check.
        let summary = client.get_protocol_summary();
        prop_assert!(
            summary.total_utilized >= 0,
            "final total_utilized must be >= 0, got {}",
            summary.total_utilized,
        );
        prop_assert_eq!(
            summary.count,
            borrowers.len() as u32,
            "count must equal the number of opened lines",
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 9 — get_credit_line idempotency
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: Two consecutive calls to `get_credit_line` with no
    /// intervening state mutation must return the same `Option<CreditLineData>`.
    ///
    /// Confirms the "pure read, no mutation" guarantee. TTL bumps may occur
    /// inside the storage layer, but logical state must be unchanged.
    #[test]
    fn prop_get_credit_line_idempotent(
        (limit, rate, score) in credit_line_params(),
        // `open_line`: whether to open a line at all (tests both Some and None).
        open_line in proptest::bool::ANY,
    ) {
        let (env, client, _admin) = setup_env();
        let borrower = Address::generate(&env);

        if open_line {
            client.open_credit_line(&borrower, &limit, &rate, &score);
        }

        let result_a = client.get_credit_line(&borrower);
        let result_b = client.get_credit_line(&borrower);

        // Both calls must return the same variant (Some / None).
        prop_assert_eq!(
            result_a.is_some(),
            result_b.is_some(),
            "get_credit_line must return the same Some/None across two reads",
        );

        if let (Some(line_a), Some(line_b)) = (result_a, result_b) {
            prop_assert_eq!(
                line_a.utilized_amount,
                line_b.utilized_amount,
                "utilized_amount must be identical across two reads",
            );
            prop_assert_eq!(
                line_a.credit_limit,
                line_b.credit_limit,
                "credit_limit must be identical across two reads",
            );
            prop_assert_eq!(
                line_a.interest_rate_bps,
                line_b.interest_rate_bps,
                "interest_rate_bps must be identical across two reads",
            );
            prop_assert_eq!(
                line_a.risk_score,
                line_b.risk_score,
                "risk_score must be identical across two reads",
            );
            prop_assert_eq!(
                line_a.status,
                line_b.status,
                "status must be identical across two reads",
            );
            prop_assert_eq!(
                line_a.accrued_interest,
                line_b.accrued_interest,
                "accrued_interest must be identical across two reads",
            );
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Proptest 10 — delinquency_applicable gate: is_delinquent ≤ delinquency_applicable
// ═══════════════════════════════════════════════════════════════════════════

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **Invariant**: `is_delinquent` can only be `true` when
    /// `delinquency_applicable` is also `true`.  That is, the gate
    /// `delinquency_applicable → is_delinquent` must hold in both directions:
    ///
    /// ```text
    /// ¬delinquency_applicable ⟹ ¬is_delinquent
    /// ```
    ///
    /// Tested with arbitrary line configurations (with and without schedule,
    /// with and without utilization) to ensure the implication is universal.
    #[test]
    fn prop_delinquency_gate_implication(
        (limit, rate, score) in credit_line_params(),
        (amt_per_period, period_secs, next_due_ts) in schedule_params(),
        attach_schedule in proptest::bool::ANY,
        time_advance in 0u64..=15_552_000u64,
    ) {
        let (env, client, _contract_id, _admin) = setup_with_token();
        let borrower = Address::generate(&env);
        client.open_credit_line(&borrower, &limit, &rate, &score);

        if attach_schedule {
            client.set_repayment_schedule(
                &borrower,
                &amt_per_period,
                &period_secs,
                &next_due_ts,
            );
        }

        // Draw a fraction of the limit to get non-zero utilization.
        let draw = (limit / 3).max(1).min(MAX_DRAW);
        let _ = client.try_draw_credit(&borrower, &draw);

        // Advance time to potentially pass due date.
        env.ledger().with_mut(|l| l.timestamp += time_advance);

        let caps = client.query_capabilities(&borrower);

        // Core implication: ¬applicable ⟹ ¬delinquent.
        if !caps.delinquency_applicable {
            prop_assert!(
                !caps.is_delinquent,
                "¬delinquency_applicable ⟹ ¬is_delinquent must hold \
                 (attach_schedule={attach_schedule}, time_advance={time_advance}s)",
            );
        }

        // Also verify consistency between capability bitmap and direct call.
        let direct = client.is_delinquent(&borrower);
        prop_assert_eq!(
            caps.is_delinquent,
            direct,
            "caps.is_delinquent must match direct is_delinquent() call",
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Edge case unit tests (deterministic)
// ═══════════════════════════════════════════════════════════════════════════

/// `get_health_factor` returns `u32::MAX` for a borrower with no credit line.
#[test]
fn health_factor_no_credit_line_returns_max() {
    let (env, client, _admin) = setup_env();
    let borrower = Address::generate(&env);

    let hf = client.get_health_factor(&borrower);
    assert_eq!(hf, u32::MAX, "no credit line → health factor must be u32::MAX");
}

/// `get_protocol_summary` on a fresh contract returns all-zero aggregates.
#[test]
fn protocol_summary_fresh_contract_all_zero() {
    let (_env, client, _admin) = setup_env();
    let summary = client.get_protocol_summary();

    assert_eq!(summary.count, 0, "no lines → count must be 0");
    assert_eq!(
        summary.total_utilized, 0,
        "no lines → total_utilized must be 0"
    );
    assert_eq!(
        summary.total_collateral, 0,
        "no lines → total_collateral must be 0"
    );
}

/// Opening a line increments `count` by 1 and does not change `total_utilized`.
#[test]
fn protocol_summary_open_line_increments_count() {
    let (env, client, _admin) = setup_env();
    let borrower = Address::generate(&env);

    let before = client.get_protocol_summary();
    client.open_credit_line(&borrower, &10_000_i128, &500_u32, &30_u32);
    let after = client.get_protocol_summary();

    assert_eq!(after.count, before.count + 1, "count must increment by 1");
    assert_eq!(
        after.total_utilized, before.total_utilized,
        "total_utilized must not change on open (no draw)"
    );
}

/// `query_capabilities` must return the same result on three consecutive calls
/// with no intervening mutations (stronger determinism check).
#[test]
fn query_capabilities_triple_call_deterministic() {
    let (env, client, _admin) = setup_env();
    let borrower = Address::generate(&env);
    client.open_credit_line(&borrower, &5_000_i128, &1_000_u32, &50_u32);

    let c1 = client.query_capabilities(&borrower);
    let c2 = client.query_capabilities(&borrower);
    let c3 = client.query_capabilities(&borrower);

    assert_eq!(c1, c2, "1st and 2nd call must match");
    assert_eq!(c2, c3, "2nd and 3rd call must match");
}

/// Capabilities reflect schedule presence: `has_repayment_schedule` must
/// toggle correctly when a schedule is set.
#[test]
fn capabilities_reflect_schedule_presence() {
    let (env, client, _admin) = setup_env();
    let borrower = Address::generate(&env);
    client.open_credit_line(&borrower, &10_000_i128, &500_u32, &30_u32);

    let caps_before = client.query_capabilities(&borrower);
    assert!(
        !caps_before.has_repayment_schedule,
        "no schedule yet → has_repayment_schedule must be false"
    );

    client.set_repayment_schedule(
        &borrower,
        &1_000_i128,
        &2_592_000_u64,
        &(INITIAL_TIMESTAMP + 2_592_000),
    );

    let caps_after = client.query_capabilities(&borrower);
    assert!(
        caps_after.has_repayment_schedule,
        "after set_repayment_schedule → has_repayment_schedule must be true"
    );
}

/// `get_credit_line` returns `None` for an address that has never had a line.
#[test]
fn get_credit_line_none_for_unknown_borrower() {
    let (env, client, _admin) = setup_env();
    let borrower = Address::generate(&env);

    let result = client.get_credit_line(&borrower);
    assert!(result.is_none(), "unknown borrower → get_credit_line must return None");
}

/// `is_delinquent` returns `false` for a borrower with zero utilization even
/// when a schedule is configured and time is past the due date.
#[test]
fn is_delinquent_false_zero_utilization_past_due() {
    let (env, client, _admin) = setup_env();
    let borrower = Address::generate(&env);
    client.open_credit_line(&borrower, &10_000_i128, &500_u32, &30_u32);

    // Set a schedule already in the past.
    let past_due = INITIAL_TIMESTAMP - 1;
    client.set_repayment_schedule(&borrower, &1_000_i128, &86_400_u64, &past_due);

    // Advance time well past the due date.
    env.ledger().with_mut(|l| l.timestamp += 86_400 * 30);

    // Zero utilization → not delinquent.
    let delinquent = client.is_delinquent(&borrower);
    assert!(
        !delinquent,
        "zero utilization → is_delinquent must be false even past due date"
    );
}

/// `get_protocol_summary` remains consistent with the number of opened lines.
#[test]
fn protocol_summary_count_tracks_opened_lines() {
    let (env, client, _admin) = setup_env();
    let n = 5_u32;

    for i in 0..n {
        let borrower = Address::generate(&env);
        client.open_credit_line(&borrower, &(1_000_i128 * (i as i128 + 1)), &500_u32, &30_u32);
        let summary = client.get_protocol_summary();
        assert_eq!(
            summary.count,
            i + 1,
            "count after {} opens must be {}",
            i + 1,
            i + 1,
        );
    }
}
